# https://github.com/firebase/firebase-tools

name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Environment Files
        run: |
          # Create the directory if it doesn't exist
          mkdir -p apps/main-app/src/environments

          # 1. Create a dummy base environment.ts file for the build to find
          echo "export const environment = { production: false, useEmulators: false, firebase: {} };" > apps/main-app/src/environments/environment.ts

          # 2. Create the real environment.prod.ts with your secrets
          echo "export const environment = { production: true, useEmulators: false, firebase: ${{ secrets.FIREBASE_CONFIG }} };" > apps/main-app/src/environments/environment.prod.ts

      - run: npm ci && npx nx build main-app

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TO_NOTE_ANGULAR_APP }}
          channelId: live
          projectId: to-note-angular-app
