name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Optimization: Explicitly set Node version + Cache NPM packages
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Create Environment Files
        run: |
          echo 'export const firebaseConfig = ${{ secrets.FIREBASE_CONFIG }};' > apps/main-app/src/environments/firebase.config.ts

      # npm ci will trigger postinstall, which will see the file above and skip the template copy.
      - run: npm ci
      - run: npx nx build main-app

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TO_NOTE_ANGULAR_APP }}
          channelId: live
          projectId: to-note-angular-app
