# https://github.com/firebase/firebase-tools

name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Environment Files
        run: |
          # Create firebase.config.ts file
          mkdir -p apps/main-app/src/environments
          echo "export const firebaseConfig = ${{ secrets.FIREBASE_CONFIG }};" > apps/main-app/src/environments/firebase.config.ts

      - run: npm ci && npx nx build main-app

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TO_NOTE_ANGULAR_APP }}
          channelId: live
          projectId: to-note-angular-app
